###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: larafood-mysql
      working_dir: /application
      # command: --default-authentication-plugin=mysql_native_password
      volumes:
        - .:/application
        - ./phpdocker/mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=larafood
        - MYSQL_USER=larafood
        - MYSQL_PASSWORD=larafood
      ports:
        - "1124:3306"

    webserver:
      image: nginx:alpine
      container_name: larafood-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1122:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: larafood-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

